repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: make lint
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
      - id: pytest
        name: run unit tests
        entry: make unit-test
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true
